version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  userinfo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userinfoservice
    depends_on:
      - mongo
      - otel-lgtm-userinfo
    env_file:
      - .env
    ports:
      - "50051:50051"
    volumes:
      - ./logs:/app/logs

  # === LGTM для UserInfo ===
  otel-lgtm-userinfo:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm-userinfo
    restart: always
    ports:
      - "13000:3000"   # Grafana
      - "13100:3100"   # Loki
      - "13200:3200"   # Tempo
      - "14317:4317"   # OTEL GRPC
      - "14318:4318"   # OTEL HTTP
      - "19090:9090"   # Prometheus
    volumes:
      - ./logs:/var/logs

  promtail-userinfo:
    image: grafana/promtail:2.8.2
    container_name: promtail-userinfo
    restart: always
    volumes:
      - ./logs:/var/log
    environment:
      - LOKI_URL=http://otel-lgtm:3100/loki/api/v1/push
      - JOB_NAME=userinfo_logs
      - LOG_PATH=/var/log/*.log
    command:
      - "-config.expand-env=true"
      - "-client.url=${LOKI_URL}"
      - "-server.http-listen-port=9080"
      - "-server.grpc-listen-port=0"
      - "-config.file="
    stdin_open: true
    tty: true

volumes:
  mongo_data: